<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: sdg6h
 * Date: Tue, 09 May 2023 21:16:23 +0000
 */

$conf['title'] = 'Physics Department Electronics Shop';
$conf['sidebar'] = 'default_sidebar_left';
$conf['license'] = 'cc-by-sa';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['mailguard'] = 'visible';
$conf['target']['extern'] = '_blank';
$conf['subscribers'] = 1;
$conf['registernotify'] = 'sgoadhouse@virginia.edu';
$conf['mailfrom'] = 'sgoadhouse@virginia.edu';
$conf['updatecheck'] = 1;
$conf['canonical'] = 1;
$conf['defer_js'] = 0;
$conf['hidewarnings'] = 1;
$conf['proxy']['user'] = 'Stephen Goadhouse';
$conf['plugin']['authldap']['attributes'] = array();
$conf['plugin']['captcha']['mode'] = 'audio';
$conf['plugin']['cloud']['minimum_word_length'] = 3;
$conf['plugin']['cloud']['tag_blacklist'] = 'indexmenu,at,tsort,js,form,noscroll,html,more,us';
$conf['plugin']['confightmlok']['use_sure'] = 1;
$conf['plugin']['confightmlok']['use_really_sure'] = 1;
$conf['plugin']['countdown']['with_hours'] = 0;
$conf['htmlok'] = '1';
$conf['phpok'] = '1';
$conf['plugin']['barcode']['showfooter'] = '1';
$conf['plugin']['contact']['default'] = 'sgoadhouse@virginia.edu';
$conf['plugin']['contact']['profile1'] = 'sgoadhouse@virginia.edu';
$conf['plugin']['google_cal']['gcal_js_ok'] = '1';
